<?php
/** @var $block Magento\Backend\Block\Template */
?>
<script>
    require([
        'order-item-actions',
        'order-coupon',
        'order-item-price-percentage',
        'order-tabs-ui',
    ], function(orderItemActions, orderCoupon, orderItemPricePercentage, orderTabsUi){
        orderItemActions.init();
        orderCoupon.init();
        orderItemPricePercentage.init();
        orderItemPricePercentage.init();
        orderTabsUi.init();
    });
</script>