<?php
/** @var $block Magento\Backend\Block\Template */
?>
<script>
    require([
        'order-item-actions',
        'order-coupon',
        'order-item-price-percentage',
        'order-tabs-ui',
        'order-save-address-book',
        'order-ship-address-validation',
    ], function(
        orderItemActions,
        orderCoupon,
        orderItemPricePercentage,
        orderTabsUi,
        orderSaveAddress,
        orderShipAddressValidation
    ){
        orderItemActions.init();
        orderCoupon.init();
        orderItemPricePercentage.init();
        orderItemPricePercentage.init();
        orderTabsUi.init();
        orderSaveAddress.init();
        orderShipAddressValidation.init();
    });
</script>
