<?php
/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid $block */
/** @var Magento\Quote\Model\Quote\Item $_item */
$_item = $block->getItem();
$originalPrice = $_item->getCalculationPrice();
if ($_item->hasCustomPrice()
    && $tierPrice = $_item->getProduct()->getPriceModel()->getTierPrice($_item->getQty(), $_item->getProduct())) {

    $originalPrice = $tierPrice;
}

?>
<div class="price-excl-tax" data-original-price="<?= $originalPrice ?>" data-current-price="<?= $_item->getCalculationPrice()?>">
    <?= /* @noEscape */ $block->formatPrice($_item->getCalculationPrice()) ?>
</div>
